#!/bin/sh
PWD=$(pwd)
if [[ $PWD == *"ippon"* ]]; then # 1)
	EMAIL=$(git config user.email)
	if [[ $EMAIL == *"ippon"* ]]; then # 2)
		echo ""
	else
		echo "email not configured to Ippon in Ippon directory"
		echo "run:"
		echo '   git config user.email "rbrugier@ipponusa.com"'
		echo ''
		exit 1 # 3)
	fi
fi
