return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "actionlint",
        "beautysh",
        "chrome-debug-adapter",
        "codelldb",
        "delve",
        "djlint",
        "eslint_d",
        "firefox-debug-adapter",
        "gofumpt",
        "goimports-reviser",
        "hadolint",
        "isort",
        "jq",
        "js-debug-adapter",
        "luacheck",
        "markdownlint",
        "php-cs-fixer",
        "php-debug-adapter",
        "phpstan",
        "prettier",
        "selene",
        "shellcheck",
        "shfmt",
        "stylua",
        "tailwindcss-language-server",
        "templ",
        "xmlformatter",
      },
    },
  },
}
